
networks:
  net-esp: 
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5082:5082"
    networks:
      - net-esp
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: "development"
      BROWSER: "none"  
    restart: always

networks:
  net-esp:
    external: true